export const ADD_ANIMAL_CHOICE = 'ADD_ANIMAL_CHOICE';
export const ADD_ENVIRONMENT_CHOICE = 'ADD_ENVIRONMENT_CHOICE';
export const ADD_LOCALGROUPS_CHOICE = 'ADD_LOCALGROUPS_CHOICE';
export const ADD_EVENTS_CHOICE = 'ADD_EVENTS_CHOICE';
