export const OPPDESCRIP_CHANGE = 'OPP_CHANGE';
export const TIMEREQ_CHANGE = 'OPP_CHANGE';
export const THING_ONE_CHANGE = 'THING_ONE_CHANGE';
export const THING_TWO_CHANGE = 'THING_TWO_CHANGE';
export const THING_THREE_CHANGE = 'THING_THREE_CHANGE';
export const OTHER_CHANGE = 'OTHER_CHANGE';
