export const UID_CHANGE = 'UID_CHANGE';
export const MATCHED_ORG_CHANGE = 'MATCHED_ORG_CHANGE';
export const OPP_CHANGE = 'OPP_CHANGE';
export const OTHER_CHANGE = 'OTHER_CHANGE';
export const QUALITIES_CHANGE = 'QUALITIES_CHANGE';
